# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logpond < Formula
  desc "TUI log viewer with built-in MCP server for AI agents"
  homepage "https://github.com/lodibrahim/logpond"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.3/logpond-darwin-amd64.tar.gz"
      sha256 "3346b86e3247513bedcbac14d43c0b89f83a10e9c0e605017916c9321818e5b7"

      define_method(:install) do
        bin.install "logpond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.3/logpond-darwin-arm64.tar.gz"
      sha256 "7c5e5adfe0e2cc881d95274298c10c206a76eb1958719484afe54ffacde9356a"

      define_method(:install) do
        bin.install "logpond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.3/logpond-linux-amd64.tar.gz"
      sha256 "3f2f16f88483bed9274a429952fdebe481492792d651da99052c127e0d029fd6"
      define_method(:install) do
        bin.install "logpond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.3/logpond-linux-arm64.tar.gz"
      sha256 "dfd13992a298d6f632c01d4ac3d2928a8c01a9cf7d8b3ae125235fa94595996f"
      define_method(:install) do
        bin.install "logpond"
      end
    end
  end
end
