# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logpond < Formula
  desc "TUI log viewer with built-in MCP server for AI agents"
  homepage "https://github.com/lodibrahim/logpond"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.2/logpond-darwin-amd64.tar.gz"
      sha256 "fd1f8bc7e8891554f69fbaf25534a9b3d71ca77b44b5d14c791de95b0e241f7d"

      define_method(:install) do
        bin.install "logpond"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.2/logpond-darwin-arm64.tar.gz"
      sha256 "b27c8087de1b0b55dc24e8eb959ed944a207e5ebcdec87dab4f51d76df298a31"

      define_method(:install) do
        bin.install "logpond"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.2/logpond-linux-amd64.tar.gz"
      sha256 "4934bc406c7dc8b4216550c9756466f8afc9b8db4ca93419f3d3e0ebb8853815"
      define_method(:install) do
        bin.install "logpond"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lodibrahim/logpond/releases/download/v0.2.2/logpond-linux-arm64.tar.gz"
      sha256 "5fd56bd5c616e635f319203f50c8fa4354c3b050bbbc9a76b39f88e04418fc1f"
      define_method(:install) do
        bin.install "logpond"
      end
    end
  end
end
