# This file was generated by GoReleaser. DO NOT EDIT.
cask "logpond" do
  name "logpond"
  desc "TUI log viewer with built-in MCP server for AI agents"
  homepage "https://github.com/lodibrahim/logpond"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logpond"

  on_macos do
    on_intel do
      url "https://github.com/lodibrahim/logpond/releases/download/v#{version}/logpond-darwin-amd64.tar.gz"
      sha256 "449cd1bed955c2acee278717dfd2e7328ee2ad36cbdad5f1f0c64746c59d23a5"
    end
    on_arm do
      url "https://github.com/lodibrahim/logpond/releases/download/v#{version}/logpond-darwin-arm64.tar.gz"
      sha256 "466253678a1e137cc6b61ad4bdda5e47d56f72f8fcc5d8fa5b7786a16afb0a60"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lodibrahim/logpond/releases/download/v#{version}/logpond-linux-amd64.tar.gz"
      sha256 "5b5f7700bd80f2e8b2119d8946611844983ad39b49c80f19af57257d6881aa97"
    end
    on_arm do
      url "https://github.com/lodibrahim/logpond/releases/download/v#{version}/logpond-linux-arm64.tar.gz"
      sha256 "feb79da6835af62347d4641172c4d898450cf816ab6b5fef010471984d285bc3"
    end
  end

  # No zap stanza required
end
